# 配置文件
system:
  host: 127.0.0.1
  port: 8080
  env: dev #生产环境
log:
  app: blog_server #生成日志服务,以及日志文件名称
  dir: logs #生成日志文件地址信息
db:
  mysql:
    username: root
    password: 1234
    host: 127.0.0.1
    port: 3306
    dbname: gin_blog
    debug: false
  mysql1:
    username: root
    password: 1234
    host: 127.0.0.1
    port: 3306
    dbname: gin_blog
    debug: false
